create table client (
	id bigint not null generated by default as identity constraint client_pkey primary key,
	nickname varchar(100),
	first_name varchar(100),
	last_name varchar(100),
	email varchar(100) not null,
	password varchar(100),
	profile_picture_uuid char(36),
	external_id char(36),
	created_at timestamp not null,
	updated_at timestamp
);