create table client (
	id bigint generated by default as identity(start with 1, increment by 1) primary key,
	nickname varchar(100),
	first_name varchar(100),
	last_name varchar(100),
	email varchar(100) not null,
	password varchar(100),
	profile_picture_uuid uuid,
	external_id uuid,
	created_at timestamp not null,
	updated_at timestamp
);