create table scheduler_history (
	id bigint not null generated by default as identity constraint scheduler_history_pkey primary key,
	started_at timestamp not null,
	ended_at timestamp,
	status_type varchar(10),
	created_at timestamp not null
);

create table migration (
	id bigint not null generated by default as identity constraint migration_pkey primary key,
	client_external_id uuid not null,
	migration_type varchar(10) not null,
	status_type varchar(10) not null,
	created_at timestamp not null
);
